### ISSUE TITLE
Request to Share Results and Suggestion for Enabling Discussions

### ISSUE THREAD

**Issue by Sad-Abd** [nicos1993/Basic-ML-Biomechanics#2]
Hi @nicos1993,

Thank you for sharing this project and making your work accessible to the community. I recently ran the script [1_BinaryClassification/main_binary_classification.py](https://github.com/nicos1993/Basic-ML-Biomechanics/blob/0a1b347179d4f854b86c8e4187ada82158e16e39/1_BinaryClassification/main_binary_classification.py) but encountered results that were less than ideal. Could you kindly share the results you achieved with any of the proposed models in this repository? This would help me ensure that my implementation and expectations are aligned with yours. 

Additionally, I noticed that the Discussions section for the repository is not enabled. Activating it might foster more interaction and provide a dedicated space for community-driven Q&A, feedback, and support.

**Comment by nicos1993** [comment]
Hello @Sad-Abd! I appreciate you taking a look into the project! I agree, if you run the code you described the results in the confusion matrix are not great... 3 are predicted correctly, 10 are predicted incorrectly. Improved results can be obtained by increasing the number of training epochs 200 => 500... this leads to 11 correct predictions and 2 incorrect.

I didn't know that was a feature! I will look into it and add it! :)

Nicos

**Comment by nicos1993** [comment]
Sorry, I marked as completed accidentally!

**Comment by nicos1993** [comment]
@Sad-Abd Discussions section has been added!

**Comment by Sad-Abd** [comment]
Thank you for your reply, @nicos1993! I also have a few suggestions I’d love to share. Let’s ignite the discussion and make this project even better! 😉
